/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationConfig: typeof import('./../src/components/application/application-config.vue')['default']
    CharSizes: typeof import('./../src/components/char-sizes.vue')['default']
    CharsMeasurer: typeof import('./../src/components/dataset/dataset-table/chars-measurer.vue')['default']
    ConfirmMenu: typeof import('./../src/components/confirm-menu.vue')['default']
    DatasetEditLineForm: typeof import('./../src/components/dataset/dataset-edit-line-form.vue')['default']
    DatasetSchemaView: typeof import('./../src/components/dataset/dataset-schema-view.vue')['default']
    DatasetTable: typeof import('./../src/components/dataset/dataset-table/dataset-table.vue')['default']
    JournalView: typeof import('./../src/components/journal-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsApiKeys: typeof import('./../src/components/settings/settings-api-keys.vue')['default']
    SettingsApiKeyUseMenu: typeof import('./../src/components/settings/settings-api-key-use-menu.vue')['default']
    SettingsLicenses: typeof import('./../src/components/settings/settings-licenses.vue')['default']
    SettingsTopics: typeof import('./../src/components/settings/settings-topics.vue')['default']
    SettingsWebhooks: typeof import('./../src/components/settings/settings-webhooks.vue')['default']
  }
}
