/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDepartmentMenu: typeof import('./../src/components/add-department-menu.vue')['default']
    AddMemberMenu: typeof import('./../src/components/add-member-menu.vue')['default']
    AddOrganizationMenu: typeof import('./../src/components/add-organization-menu.vue')['default']
    AddPartnerMenu: typeof import('./../src/components/add-partner-menu.vue')['default']
    AuthProvidersLoginLinks: typeof import('./../src/components/auth-providers-login-links.vue')['default']
    CancelDeletion: typeof import('./../src/components/cancel-deletion.vue')['default']
    ChangeHost: typeof import('./../src/components/change-host.vue')['default']
    ColorsPreview: typeof import('./../src/components/colors-preview.vue')['default']
    ConfirmMenu: typeof import('./../src/components/confirm-menu.vue')['default']
    DeleteDepartmentMenu: typeof import('./../src/components/delete-department-menu.vue')['default']
    DeleteMemberMenu: typeof import('./../src/components/delete-member-menu.vue')['default']
    DeletePartnerMenu: typeof import('./../src/components/delete-partner-menu.vue')['default']
    EditDepartmentMenu: typeof import('./../src/components/edit-department-menu.vue')['default']
    EditDepartmentsMenu: typeof import('./../src/components/edit-departments-menu.vue')['default']
    EditMemberMenu: typeof import('./../src/components/edit-member-menu.vue')['default']
    LayoutAppBar: typeof import('./../src/components/layout/layout-app-bar.vue')['default']
    LoadAvatar: typeof import('./../src/components/load-avatar.vue')['default']
    Logo: typeof import('./../src/components/logo.vue')['default']
    NotifyMenu: typeof import('./../src/components/notify-menu.vue')['default']
    OrganizationDepartments: typeof import('./../src/components/organization-departments.vue')['default']
    OrganizationMembers: typeof import('./../src/components/organization-members.vue')['default']
    OrganizationPartners: typeof import('./../src/components/organization-partners.vue')['default']
    OrganizationStorage: typeof import('./../src/components/organization-storage.vue')['default']
    PartnerInvitation: typeof import('./../src/components/partner-invitation.vue')['default']
    ResendInvitation: typeof import('./../src/components/resend-invitation.vue')['default']
    ResendPartnerInvitation: typeof import('./../src/components/resend-partner-invitation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SitePatch: typeof import('./../src/components/site-patch.vue')['default']
    SitePost: typeof import('./../src/components/site-post.vue')['default']
  }
}
