/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dev': RouteRecordInfo<'/dev', '/dev', Record<never, never>, Record<never, never>>,
    '/embed/application/[id]/config': RouteRecordInfo<'/embed/application/[id]/config', '/embed/application/:id/config', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/embed/dataset/[id]/fields': RouteRecordInfo<'/embed/dataset/[id]/fields', '/embed/dataset/:id/fields', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/embed/dataset/[id]/form': RouteRecordInfo<'/embed/dataset/[id]/form', '/embed/dataset/:id/form', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/embed/dataset/[id]/journal': RouteRecordInfo<'/embed/dataset/[id]/journal', '/embed/dataset/:id/journal', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/embed/dataset/[id]/map': RouteRecordInfo<'/embed/dataset/[id]/map', '/embed/dataset/:id/map', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/embed/dataset/[id]/table': RouteRecordInfo<'/embed/dataset/[id]/table', '/embed/dataset/:id/table', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/embed/settings/[type]/[id]/api-keys': RouteRecordInfo<'/embed/settings/[type]/[id]/api-keys', '/embed/settings/:type/:id/api-keys', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/embed/settings/[type]/[id]/licenses': RouteRecordInfo<'/embed/settings/[type]/[id]/licenses', '/embed/settings/:type/:id/licenses', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/embed/settings/[type]/[id]/topics': RouteRecordInfo<'/embed/settings/[type]/[id]/topics', '/embed/settings/:type/:id/topics', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/embed/settings/[type]/[id]/webhooks': RouteRecordInfo<'/embed/settings/[type]/[id]/webhooks', '/embed/settings/:type/:id/webhooks', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
  }
}
