/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/base-apps': RouteRecordInfo<
      '/embed/admin/base-apps',
      '/embed/admin/base-apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/errors': RouteRecordInfo<
      '/embed/admin/errors',
      '/embed/admin/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/info': RouteRecordInfo<
      '/embed/admin/info',
      '/embed/admin/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/owners': RouteRecordInfo<
      '/embed/admin/owners',
      '/embed/admin/owners',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/application/[id]/config': RouteRecordInfo<
      '/embed/application/[id]/config',
      '/embed/application/:id/config',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/download': RouteRecordInfo<
      '/embed/dataset/[id]/download',
      '/embed/dataset/:id/download',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/fields': RouteRecordInfo<
      '/embed/dataset/[id]/fields',
      '/embed/dataset/:id/fields',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/form': RouteRecordInfo<
      '/embed/dataset/[id]/form',
      '/embed/dataset/:id/form',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/journal': RouteRecordInfo<
      '/embed/dataset/[id]/journal',
      '/embed/dataset/:id/journal',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/map': RouteRecordInfo<
      '/embed/dataset/[id]/map',
      '/embed/dataset/:id/map',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/map-bounds': RouteRecordInfo<
      '/embed/dataset/[id]/map-bounds',
      '/embed/dataset/:id/map-bounds',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/publication-sites': RouteRecordInfo<
      '/embed/dataset/[id]/publication-sites',
      '/embed/dataset/:id/publication-sites',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/related-datasets': RouteRecordInfo<
      '/embed/dataset/[id]/related-datasets',
      '/embed/dataset/:id/related-datasets',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/search-files': RouteRecordInfo<
      '/embed/dataset/[id]/search-files',
      '/embed/dataset/:id/search-files',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/table': RouteRecordInfo<
      '/embed/dataset/[id]/table',
      '/embed/dataset/:id/table',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/table-edit': RouteRecordInfo<
      '/embed/dataset/[id]/table-edit',
      '/embed/dataset/:id/table-edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/thumbnails': RouteRecordInfo<
      '/embed/dataset/[id]/thumbnails',
      '/embed/dataset/:id/thumbnails',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dev': RouteRecordInfo<
      '/embed/dev',
      '/embed/dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/remote-services/': RouteRecordInfo<
      '/embed/remote-services/',
      '/embed/remote-services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/remote-services/[id]/': RouteRecordInfo<
      '/embed/remote-services/[id]/',
      '/embed/remote-services/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/settings/': RouteRecordInfo<
      '/embed/settings/',
      '/embed/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/settings/[type]/[id]/api-keys': RouteRecordInfo<
      '/embed/settings/[type]/[id]/api-keys',
      '/embed/settings/:type/:id/api-keys',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/datasets-metadata': RouteRecordInfo<
      '/embed/settings/[type]/[id]/datasets-metadata',
      '/embed/settings/:type/:id/datasets-metadata',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/licenses': RouteRecordInfo<
      '/embed/settings/[type]/[id]/licenses',
      '/embed/settings/:type/:id/licenses',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/topics': RouteRecordInfo<
      '/embed/settings/[type]/[id]/topics',
      '/embed/settings/:type/:id/topics',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/webhooks': RouteRecordInfo<
      '/embed/settings/[type]/[id]/webhooks',
      '/embed/settings/:type/:id/webhooks',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/storage': RouteRecordInfo<
      '/embed/storage',
      '/embed/storage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/workflow/update-dataset': RouteRecordInfo<
      '/embed/workflow/update-dataset',
      '/embed/workflow/update-dataset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/embed/admin/base-apps.vue': {
      routes:
        | '/embed/admin/base-apps'
      views:
        | never
    }
    'src/pages/embed/admin/errors.vue': {
      routes:
        | '/embed/admin/errors'
      views:
        | never
    }
    'src/pages/embed/admin/info.vue': {
      routes:
        | '/embed/admin/info'
      views:
        | never
    }
    'src/pages/embed/admin/owners.vue': {
      routes:
        | '/embed/admin/owners'
      views:
        | never
    }
    'src/pages/embed/application/[id]/config.vue': {
      routes:
        | '/embed/application/[id]/config'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/download.vue': {
      routes:
        | '/embed/dataset/[id]/download'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/fields.vue': {
      routes:
        | '/embed/dataset/[id]/fields'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/form.vue': {
      routes:
        | '/embed/dataset/[id]/form'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/journal.vue': {
      routes:
        | '/embed/dataset/[id]/journal'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/map.vue': {
      routes:
        | '/embed/dataset/[id]/map'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/map-bounds.vue': {
      routes:
        | '/embed/dataset/[id]/map-bounds'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/publication-sites.vue': {
      routes:
        | '/embed/dataset/[id]/publication-sites'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/related-datasets.vue': {
      routes:
        | '/embed/dataset/[id]/related-datasets'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/search-files.vue': {
      routes:
        | '/embed/dataset/[id]/search-files'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/table.vue': {
      routes:
        | '/embed/dataset/[id]/table'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/table-edit.vue': {
      routes:
        | '/embed/dataset/[id]/table-edit'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/thumbnails.vue': {
      routes:
        | '/embed/dataset/[id]/thumbnails'
      views:
        | never
    }
    'src/pages/embed/dev.vue': {
      routes:
        | '/embed/dev'
      views:
        | never
    }
    'src/pages/embed/remote-services/index.vue': {
      routes:
        | '/embed/remote-services/'
      views:
        | never
    }
    'src/pages/embed/remote-services/[id]/index.vue': {
      routes:
        | '/embed/remote-services/[id]/'
      views:
        | never
    }
    'src/pages/embed/settings/index.vue': {
      routes:
        | '/embed/settings/'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/api-keys.vue': {
      routes:
        | '/embed/settings/[type]/[id]/api-keys'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/datasets-metadata.vue': {
      routes:
        | '/embed/settings/[type]/[id]/datasets-metadata'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/licenses.vue': {
      routes:
        | '/embed/settings/[type]/[id]/licenses'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/topics.vue': {
      routes:
        | '/embed/settings/[type]/[id]/topics'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/webhooks.vue': {
      routes:
        | '/embed/settings/[type]/[id]/webhooks'
      views:
        | never
    }
    'src/pages/embed/storage.vue': {
      routes:
        | '/embed/storage'
      views:
        | never
    }
    'src/pages/embed/workflow/update-dataset.vue': {
      routes:
        | '/embed/workflow/update-dataset'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
