/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/catalogs-plugins': RouteRecordInfo<
      '/admin/catalogs-plugins',
      '/admin/catalogs-plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/processings-plugins': RouteRecordInfo<
      '/admin/processings-plugins',
      '/admin/processings-plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin-extra/[id]': RouteRecordInfo<
      '/admin-extra/[id]',
      '/admin-extra/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/agents': RouteRecordInfo<
      '/agents',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-doc': RouteRecordInfo<
      '/api-doc',
      '/api-doc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/application/[id]/': RouteRecordInfo<
      '/application/[id]/',
      '/application/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/application/[id]/api-doc': RouteRecordInfo<
      '/application/[id]/api-doc',
      '/application/:id/api-doc',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/application/[id]/config': RouteRecordInfo<
      '/application/[id]/config',
      '/application/:id/config',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/applications': RouteRecordInfo<
      '/applications',
      '/applications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalogs': RouteRecordInfo<
      '/catalogs',
      '/catalogs',
      Record<never, never>,
      Record<never, never>,
      | '/catalogs/[...page]'
    >,
    '/catalogs/[...page]': RouteRecordInfo<
      '/catalogs/[...page]',
      '/catalogs/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/': RouteRecordInfo<
      '/dataset/[id]/',
      '/dataset/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/api-doc': RouteRecordInfo<
      '/dataset/[id]/api-doc',
      '/dataset/:id/api-doc',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/data': RouteRecordInfo<
      '/dataset/[id]/data',
      '/dataset/:id/data',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/edit-data': RouteRecordInfo<
      '/dataset/[id]/edit-data',
      '/dataset/:id/edit-data',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/edit-metadata': RouteRecordInfo<
      '/dataset/[id]/edit-metadata',
      '/dataset/:id/edit-metadata',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/files': RouteRecordInfo<
      '/dataset/[id]/files',
      '/dataset/:id/files',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/map': RouteRecordInfo<
      '/dataset/[id]/map',
      '/dataset/:id/map',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/revisions': RouteRecordInfo<
      '/dataset/[id]/revisions',
      '/dataset/:id/revisions',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/table': RouteRecordInfo<
      '/dataset/[id]/table',
      '/dataset/:id/table',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dataset/[id]/thumbnails': RouteRecordInfo<
      '/dataset/[id]/thumbnails',
      '/dataset/:id/thumbnails',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/datasets': RouteRecordInfo<
      '/datasets',
      '/datasets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/department': RouteRecordInfo<
      '/department',
      '/department',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/base-apps': RouteRecordInfo<
      '/embed/admin/base-apps',
      '/embed/admin/base-apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/errors': RouteRecordInfo<
      '/embed/admin/errors',
      '/embed/admin/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/info': RouteRecordInfo<
      '/embed/admin/info',
      '/embed/admin/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/admin/owners': RouteRecordInfo<
      '/embed/admin/owners',
      '/embed/admin/owners',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/application/[id]/config': RouteRecordInfo<
      '/embed/application/[id]/config',
      '/embed/application/:id/config',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/download': RouteRecordInfo<
      '/embed/dataset/[id]/download',
      '/embed/dataset/:id/download',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/fields': RouteRecordInfo<
      '/embed/dataset/[id]/fields',
      '/embed/dataset/:id/fields',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/form': RouteRecordInfo<
      '/embed/dataset/[id]/form',
      '/embed/dataset/:id/form',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/journal': RouteRecordInfo<
      '/embed/dataset/[id]/journal',
      '/embed/dataset/:id/journal',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/map': RouteRecordInfo<
      '/embed/dataset/[id]/map',
      '/embed/dataset/:id/map',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/map-bounds': RouteRecordInfo<
      '/embed/dataset/[id]/map-bounds',
      '/embed/dataset/:id/map-bounds',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/publication-sites': RouteRecordInfo<
      '/embed/dataset/[id]/publication-sites',
      '/embed/dataset/:id/publication-sites',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/related-datasets': RouteRecordInfo<
      '/embed/dataset/[id]/related-datasets',
      '/embed/dataset/:id/related-datasets',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/search-files': RouteRecordInfo<
      '/embed/dataset/[id]/search-files',
      '/embed/dataset/:id/search-files',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/table': RouteRecordInfo<
      '/embed/dataset/[id]/table',
      '/embed/dataset/:id/table',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/table-edit': RouteRecordInfo<
      '/embed/dataset/[id]/table-edit',
      '/embed/dataset/:id/table-edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dataset/[id]/thumbnails': RouteRecordInfo<
      '/embed/dataset/[id]/thumbnails',
      '/embed/dataset/:id/thumbnails',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/dev': RouteRecordInfo<
      '/embed/dev',
      '/embed/dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/remote-services/': RouteRecordInfo<
      '/embed/remote-services/',
      '/embed/remote-services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/embed/remote-services/[id]/': RouteRecordInfo<
      '/embed/remote-services/[id]/',
      '/embed/remote-services/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/api-keys': RouteRecordInfo<
      '/embed/settings/[type]/[id]/api-keys',
      '/embed/settings/:type/:id/api-keys',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/datasets-metadata': RouteRecordInfo<
      '/embed/settings/[type]/[id]/datasets-metadata',
      '/embed/settings/:type/:id/datasets-metadata',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/licenses': RouteRecordInfo<
      '/embed/settings/[type]/[id]/licenses',
      '/embed/settings/:type/:id/licenses',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/topics': RouteRecordInfo<
      '/embed/settings/[type]/[id]/topics',
      '/embed/settings/:type/:id/topics',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/settings/[type]/[id]/webhooks': RouteRecordInfo<
      '/embed/settings/[type]/[id]/webhooks',
      '/embed/settings/:type/:id/webhooks',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/embed/workflow/update-dataset': RouteRecordInfo<
      '/embed/workflow/update-dataset',
      '/embed/workflow/update-dataset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/events': RouteRecordInfo<
      '/events',
      '/events',
      Record<never, never>,
      Record<never, never>,
      | '/events/[...page]'
    >,
    '/events/[...page]': RouteRecordInfo<
      '/events/[...page]',
      '/events/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/extra/[id]': RouteRecordInfo<
      '/extra/[id]',
      '/extra/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/me': RouteRecordInfo<
      '/me',
      '/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/metrics': RouteRecordInfo<
      '/metrics',
      '/metrics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/new-application': RouteRecordInfo<
      '/new-application',
      '/new-application',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/new-dataset': RouteRecordInfo<
      '/new-dataset',
      '/new-dataset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notifications': RouteRecordInfo<
      '/notifications',
      '/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization': RouteRecordInfo<
      '/organization',
      '/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pages': RouteRecordInfo<
      '/pages',
      '/pages',
      Record<never, never>,
      Record<never, never>,
      | '/pages/[...page]'
    >,
    '/pages/[...page]': RouteRecordInfo<
      '/pages/[...page]',
      '/pages/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/portals': RouteRecordInfo<
      '/portals',
      '/portals',
      Record<never, never>,
      Record<never, never>,
      | '/portals/[...page]'
    >,
    '/portals/[...page]': RouteRecordInfo<
      '/portals/[...page]',
      '/portals/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/processings': RouteRecordInfo<
      '/processings',
      '/processings',
      Record<never, never>,
      Record<never, never>,
      | '/processings/[...page]'
    >,
    '/processings/[...page]': RouteRecordInfo<
      '/processings/[...page]',
      '/processings/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/reuses': RouteRecordInfo<
      '/reuses',
      '/reuses',
      Record<never, never>,
      Record<never, never>,
      | '/reuses/[...page]'
    >,
    '/reuses/[...page]': RouteRecordInfo<
      '/reuses/[...page]',
      '/reuses/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/share-dataset': RouteRecordInfo<
      '/share-dataset',
      '/share-dataset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/storage': RouteRecordInfo<
      '/storage',
      '/storage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subscription': RouteRecordInfo<
      '/subscription',
      '/subscription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/update-dataset': RouteRecordInfo<
      '/update-dataset',
      '/update-dataset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/catalogs-plugins.vue': {
      routes:
        | '/admin/catalogs-plugins'
      views:
        | never
    }
    'src/pages/admin/processings-plugins.vue': {
      routes:
        | '/admin/processings-plugins'
      views:
        | never
    }
    'src/pages/admin-extra/[id].vue': {
      routes:
        | '/admin-extra/[id]'
      views:
        | never
    }
    'src/pages/agents.vue': {
      routes:
        | '/agents'
      views:
        | never
    }
    'src/pages/api-doc.vue': {
      routes:
        | '/api-doc'
      views:
        | never
    }
    'src/pages/application/[id]/index.vue': {
      routes:
        | '/application/[id]/'
      views:
        | never
    }
    'src/pages/application/[id]/api-doc.vue': {
      routes:
        | '/application/[id]/api-doc'
      views:
        | never
    }
    'src/pages/application/[id]/config.vue': {
      routes:
        | '/application/[id]/config'
      views:
        | never
    }
    'src/pages/applications.vue': {
      routes:
        | '/applications'
      views:
        | never
    }
    'src/pages/catalogs.vue': {
      routes:
        | '/catalogs'
        | '/catalogs/[...page]'
      views:
        | 'default'
    }
    'src/pages/catalogs/[...page].vue': {
      routes:
        | '/catalogs/[...page]'
      views:
        | never
    }
    'src/pages/dataset/[id]/index.vue': {
      routes:
        | '/dataset/[id]/'
      views:
        | never
    }
    'src/pages/dataset/[id]/api-doc.vue': {
      routes:
        | '/dataset/[id]/api-doc'
      views:
        | never
    }
    'src/pages/dataset/[id]/data.vue': {
      routes:
        | '/dataset/[id]/data'
      views:
        | never
    }
    'src/pages/dataset/[id]/edit-data.vue': {
      routes:
        | '/dataset/[id]/edit-data'
      views:
        | never
    }
    'src/pages/dataset/[id]/edit-metadata.vue': {
      routes:
        | '/dataset/[id]/edit-metadata'
      views:
        | never
    }
    'src/pages/dataset/[id]/files.vue': {
      routes:
        | '/dataset/[id]/files'
      views:
        | never
    }
    'src/pages/dataset/[id]/map.vue': {
      routes:
        | '/dataset/[id]/map'
      views:
        | never
    }
    'src/pages/dataset/[id]/revisions.vue': {
      routes:
        | '/dataset/[id]/revisions'
      views:
        | never
    }
    'src/pages/dataset/[id]/table.vue': {
      routes:
        | '/dataset/[id]/table'
      views:
        | never
    }
    'src/pages/dataset/[id]/thumbnails.vue': {
      routes:
        | '/dataset/[id]/thumbnails'
      views:
        | never
    }
    'src/pages/datasets.vue': {
      routes:
        | '/datasets'
      views:
        | never
    }
    'src/pages/department.vue': {
      routes:
        | '/department'
      views:
        | never
    }
    'src/pages/embed/admin/base-apps.vue': {
      routes:
        | '/embed/admin/base-apps'
      views:
        | never
    }
    'src/pages/embed/admin/errors.vue': {
      routes:
        | '/embed/admin/errors'
      views:
        | never
    }
    'src/pages/embed/admin/info.vue': {
      routes:
        | '/embed/admin/info'
      views:
        | never
    }
    'src/pages/embed/admin/owners.vue': {
      routes:
        | '/embed/admin/owners'
      views:
        | never
    }
    'src/pages/embed/application/[id]/config.vue': {
      routes:
        | '/embed/application/[id]/config'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/download.vue': {
      routes:
        | '/embed/dataset/[id]/download'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/fields.vue': {
      routes:
        | '/embed/dataset/[id]/fields'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/form.vue': {
      routes:
        | '/embed/dataset/[id]/form'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/journal.vue': {
      routes:
        | '/embed/dataset/[id]/journal'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/map.vue': {
      routes:
        | '/embed/dataset/[id]/map'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/map-bounds.vue': {
      routes:
        | '/embed/dataset/[id]/map-bounds'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/publication-sites.vue': {
      routes:
        | '/embed/dataset/[id]/publication-sites'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/related-datasets.vue': {
      routes:
        | '/embed/dataset/[id]/related-datasets'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/search-files.vue': {
      routes:
        | '/embed/dataset/[id]/search-files'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/table.vue': {
      routes:
        | '/embed/dataset/[id]/table'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/table-edit.vue': {
      routes:
        | '/embed/dataset/[id]/table-edit'
      views:
        | never
    }
    'src/pages/embed/dataset/[id]/thumbnails.vue': {
      routes:
        | '/embed/dataset/[id]/thumbnails'
      views:
        | never
    }
    'src/pages/embed/dev.vue': {
      routes:
        | '/embed/dev'
      views:
        | never
    }
    'src/pages/embed/remote-services/index.vue': {
      routes:
        | '/embed/remote-services/'
      views:
        | never
    }
    'src/pages/embed/remote-services/[id]/index.vue': {
      routes:
        | '/embed/remote-services/[id]/'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/api-keys.vue': {
      routes:
        | '/embed/settings/[type]/[id]/api-keys'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/datasets-metadata.vue': {
      routes:
        | '/embed/settings/[type]/[id]/datasets-metadata'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/licenses.vue': {
      routes:
        | '/embed/settings/[type]/[id]/licenses'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/topics.vue': {
      routes:
        | '/embed/settings/[type]/[id]/topics'
      views:
        | never
    }
    'src/pages/embed/settings/[type]/[id]/webhooks.vue': {
      routes:
        | '/embed/settings/[type]/[id]/webhooks'
      views:
        | never
    }
    'src/pages/embed/workflow/update-dataset.vue': {
      routes:
        | '/embed/workflow/update-dataset'
      views:
        | never
    }
    'src/pages/events.vue': {
      routes:
        | '/events'
        | '/events/[...page]'
      views:
        | 'default'
    }
    'src/pages/events/[...page].vue': {
      routes:
        | '/events/[...page]'
      views:
        | never
    }
    'src/pages/extra/[id].vue': {
      routes:
        | '/extra/[id]'
      views:
        | never
    }
    'src/pages/me.vue': {
      routes:
        | '/me'
      views:
        | never
    }
    'src/pages/metrics.vue': {
      routes:
        | '/metrics'
      views:
        | never
    }
    'src/pages/new-application.vue': {
      routes:
        | '/new-application'
      views:
        | never
    }
    'src/pages/new-dataset.vue': {
      routes:
        | '/new-dataset'
      views:
        | never
    }
    'src/pages/notifications.vue': {
      routes:
        | '/notifications'
      views:
        | never
    }
    'src/pages/organization.vue': {
      routes:
        | '/organization'
      views:
        | never
    }
    'src/pages/pages.vue': {
      routes:
        | '/pages'
        | '/pages/[...page]'
      views:
        | 'default'
    }
    'src/pages/pages/[...page].vue': {
      routes:
        | '/pages/[...page]'
      views:
        | never
    }
    'src/pages/portals.vue': {
      routes:
        | '/portals'
        | '/portals/[...page]'
      views:
        | 'default'
    }
    'src/pages/portals/[...page].vue': {
      routes:
        | '/portals/[...page]'
      views:
        | never
    }
    'src/pages/processings.vue': {
      routes:
        | '/processings'
        | '/processings/[...page]'
      views:
        | 'default'
    }
    'src/pages/processings/[...page].vue': {
      routes:
        | '/processings/[...page]'
      views:
        | never
    }
    'src/pages/reuses.vue': {
      routes:
        | '/reuses'
        | '/reuses/[...page]'
      views:
        | 'default'
    }
    'src/pages/reuses/[...page].vue': {
      routes:
        | '/reuses/[...page]'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/share-dataset.vue': {
      routes:
        | '/share-dataset'
      views:
        | never
    }
    'src/pages/storage.vue': {
      routes:
        | '/storage'
      views:
        | never
    }
    'src/pages/subscription.vue': {
      routes:
        | '/subscription'
      views:
        | never
    }
    'src/pages/update-dataset.vue': {
      routes:
        | '/update-dataset'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
