#!/bin/bash

set -x # trace all commandes

RANDOM_NB=$((1024 + RANDOM % 48000))

cat <<EOF > ".env"
NGINX_PORT1=$((RANDOM_NB))
NGINX_PORT2=$((RANDOM_NB + 1))

DEV_API_PORT=$((RANDOM_NB + 10))
DEV_UI_PORT=$((RANDOM_NB + 11))
DEV_OBSERVER_PORT=$((RANDOM_NB + 12))

ES_PORT=$((RANDOM_NB + 20))
MONGO_PORT=$((RANDOM_NB + 21))
S3_PORT=$((RANDOM_NB + 22))
CLAMAV_PORT=$((RANDOM_NB + 23))

SD_PORT=$((RANDOM_NB + 30))
EVENTS_PORT=$((RANDOM_NB + 31))
OAV_PORT=$((RANDOM_NB + 32))
CAPTURE_PORT=$((RANDOM_NB + 33))
CATALOGS_PORT=$((RANDOM_NB + 34))
EOF