import { strict as assert } from 'node:assert'
import { it, describe, before, after, beforeEach, afterEach } from 'node:test'
import { startApiServer, stopApiServer, scratchData, checkPendingTasks, dmeadus, sendDataset } from './utils/index.ts'

describe('search', function () {
  before(startApiServer)
  beforeEach(scratchData)
  after(stopApiServer)
  afterEach((t) => checkPendingTasks(t.name))

  it('Get lines in dataset', async function () {
    const ax = dmeadus
    const dataset = await sendDataset('datasets/dataset1.csv', ax)
    const locProp = dataset.schema.find((p: any) => p.key === 'loc')
    locProp['x-refersTo'] = 'http://www.w3.org/2003/01/geo/wgs84_pos#lat_long'
    let res = await ax.patch('/api/v1/datasets/' + dataset.id, { schema: dataset.schema })
    assert.equal(res.status, 200)
    const workers = await import('../api/src/workers/index.ts')
    await workers.hook(`finalize/${dataset.id}`)

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`)
    assert.equal(res.data.total, 2)

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?q=koumoul`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?q=Koumoul`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?q=lactée`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?q=lacté`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?q=lacté&q_fields=adr`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?q=lacté&q_fields=id`)
    assert.equal(res.data.total, 0)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_in=koumoul,test`)
    assert.equal(res.data.total, 1)
    assert.equal(res.data.results[0].id, 'koumoul')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_eq=koumoul`)
    assert.equal(res.data.total, 1)
    assert.equal(res.data.results[0].id, 'koumoul')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_nin=koumoul,test`)
    assert.equal(res.data.total, 1)
    assert.equal(res.data.results[0].id, 'bidule')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_neq=koumoul`)
    assert.equal(res.data.total, 1)
    assert.equal(res.data.results[0].id, 'bidule')

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`, { params: { adr_search: 'lactée' } })
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`, { params: { adr_search: 'lactée inconnue' } })
    assert.equal(res.data.total, 2)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`, { params: { adr_search: 'lactée +inconnue' } })
    assert.equal(res.data.total, 0)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`, { params: { adr_search: 'lacté' } })
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`, { params: { adr_search: 'koumoul' } })
    assert.equal(res.data.total, 0)
    await assert.rejects(ax.get(`/api/v1/datasets/${dataset.id}/lines?id_contains=oumou`), { status: 400 })
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_starts=kou`)
    assert.equal(res.data.total, 1)
    await assert.rejects(ax.get(`/api/v1/datasets/${dataset.id}/lines?BADFIELD_in=koumoul`), (err: any) => {
      assert.equal(err.status, 400)
      return true
    })
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_gt=cc`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_gte=cc`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?some_date_gt=2017-11-12`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?nb_gt=22`)
    assert.equal(res.data.total, 1)

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?bbox=-2.5,40,3,47`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?geo_distance=-2.75,47.7,10km`)
    assert.ok(res.data.results[0]._geo_distance > 1400)
    assert.ok(res.data.results[0]._geo_distance < 1500)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?geo_distance=-2.75:47.7:10km`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?geo_distance=-2.74,47.7,1`)
    assert.equal(res.data.total, 0)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?geo_distance=-2.748526,47.687375`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?sort=_geo_distance:2.6:45.5`)
    assert.equal(res.data.results[0].id, 'bidule')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?sort=-_geo_distance:2.6:45.5`)
    assert.equal(res.data.results[0].id, 'koumoul')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?geo_distance=2.6,45.5,1000km`)
    assert.equal(res.data.total, 2)
    assert.equal(res.data.results[0].id, 'bidule')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?geo_distance=-2.748526,47.687375,1000km`)
    assert.equal(res.data.total, 2)
    assert.equal(res.data.results[0].id, 'koumoul')

    res = await ax.get(`/api/v1/datasets/${dataset.id}/geo_agg?bbox=-3,47,-2,48`)
    assert.equal(res.status, 200)
    assert.equal(res.data.aggs.length, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/geo_agg?bbox=-3,45,3,48`)
    assert.equal(res.status, 200)
    assert.equal(res.data.aggs.length, 2)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?xyz=63,44,7`)
    assert.equal(res.data.total, 1)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?xyz=63,44,7&format=geojson`)
    assert.equal(res.data.total, 1)
    assert.equal(res.data.features.length, 1)
    assert.ok(res.data.features[0].geometry)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?xyz=63,44,7&format=pbf&q=koumoul`)
    assert.equal(res.status, 200)
    assert.equal(res.headers['content-type'], 'application/x-protobuf')
    assert.equal(res.headers['x-tilesmode'], 'es/neighbors/10000')
    assert.equal(res.headers['x-tilesampling'], '1/1')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?xyz=3,4,7&format=pbf`)
    assert.equal(res.status, 204)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?xyz=63,44,7&format=pbf&q=koumoul&sampling=max`)
    assert.equal(res.status, 200)
    assert.equal(res.headers['content-type'], 'application/x-protobuf')
    assert.equal(res.headers['x-tilesmode'], 'es/max')
    assert.equal(res.headers['x-tilesampling'], '1/1')

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?format=csv`)
    assert.equal(res.headers['content-type'], 'text/csv; charset=utf-8')
    let csvLines = res.data.split('\n')
    assert.equal(csvLines[0].trim(), '"id","adr","some date","loc","bool","nb"')
    assert.equal(csvLines[1], '"koumoul","19 rue de la voie lactée saint avé","2017-12-12","47.687375,-2.748526",0,11')
    locProp.title = 'Localisation'
    await ax.patch('/api/v1/datasets/' + dataset.id, { schema: dataset.schema })
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?format=csv`)
    csvLines = res.data.split('\n')
    assert.equal(csvLines[0].trim(), '"id","adr","some date","loc","bool","nb"')
    assert.equal(csvLines[1], '"koumoul","19 rue de la voie lactée saint avé","2017-12-12","47.687375,-2.748526",0,11')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?format=csv&sep=;`)
    csvLines = res.data.split('\n')
    assert.equal(csvLines[0].trim(), '"id";"adr";"some date";"loc";"bool";"nb"')

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?format=xlsx`)
    assert.equal(res.headers['content-disposition'], 'attachment; filename="dataset1.xlsx"')
    assert.equal(res.headers['content-type'], 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    assert.ok(Number(res.headers['content-length']) > 5000)
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?format=ods`)
    assert.equal(res.headers['content-disposition'], 'attachment; filename="dataset1.ods"')
    assert.equal(res.headers['content-type'], 'application/vnd.oasis.opendocument.spreadsheet')
    assert.ok(Number(res.headers['content-length']) > 5000)
  })

  it('Filter on line existence', async function () {
    const ax = dmeadus
    const dataset = await sendDataset('datasets/dataset2.csv', ax)

    let res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`)
    assert.equal(res.data.total, 6)

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_exists`)
    assert.equal(res.data.total, 5)
    assert.equal(res.data.results[0].id, 'koumoul')
    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?id_nexists`)
    assert.equal(res.data.total, 1)
    assert.equal(res.data.results[0].adr, 'missing id')
  })

  it('search lines and collapse on field', async function () {
    const ax = dmeadus
    const workers = await import('../api/src/workers/index.ts')
    const dataset = await sendDataset('datasets/collapsable.csv', ax)

    let res = await ax.get(`/api/v1/datasets/${dataset.id}/lines`)
    assert.equal(res.data.total, 10)

    res = await ax.get(`/api/v1/datasets/${dataset.id}/lines?collapse=group&size=2&page=2`)
    assert.equal(res.data.totalCollapse, 4)
    assert.equal(res.data.total, 10)
    assert.equal(res.data.results[0].group, 'group3')
    assert.equal(res.data.results[0].grouplabel, 'group 3')

    const rolesProp = dataset.schema.find((p: any) => p.key === 'roles')
    rolesProp.separator = ' ; '
    await ax.patch('/api/v1/datasets/' + dataset.id, { schema: dataset.schema })
    await workers.hook('finalize/' + dataset.id)

    await assert.rejects(ax.get(`/api/v1/datasets/${dataset.id}/lines?collapse=roles`), { status: 400 })
  })
})
