/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationConfig: typeof import('./../src/components/application/application-config.vue')['default']
    CharsMeasurer: typeof import('./../src/components/dataset/table/chars-measurer.vue')['default']
    ConfirmMenu: typeof import('./../src/components/confirm-menu.vue')['default']
    DatasetCard: typeof import('./../src/components/dataset/dataset-card.vue')['default']
    DatasetDownloadCsvOptions: typeof import('./../src/components/dataset/dataset-download-csv-options.vue')['default']
    DatasetDownloadResults: typeof import('./../src/components/dataset/dataset-download-results.vue')['default']
    DatasetEditLineForm: typeof import('./../src/components/dataset/form/dataset-edit-line-form.vue')['default']
    DatasetEditMultipleLines: typeof import('./../src/components/dataset/form/dataset-edit-multiple-lines.vue')['default']
    DatasetFileFormats: typeof import('./../src/components/dataset/dataset-file-formats.vue')['default']
    DatasetFilters: typeof import('./../src/components/dataset/dataset-filters.vue')['default']
    DatasetItemCard: typeof import('./../src/components/dataset/dataset-item-card.vue')['default']
    DatasetItemDetailDialog: typeof import('./../src/components/dataset/dataset-item-detail-dialog.vue')['default']
    DatasetItemValue: typeof import('./../src/components/dataset/dataset-item-value.vue')['default']
    DatasetItemValueMultiple: typeof import('./../src/components/dataset/dataset-item-value-multiple.vue')['default']
    DatasetMap: typeof import('./../src/components/dataset/map/dataset-map.vue')['default']
    DatasetMapBounds: typeof import('./../src/components/dataset/map/dataset-map-bounds.vue')['default']
    DatasetNbResults: typeof import('./../src/components/dataset/dataset-nb-results.vue')['default']
    DatasetPublicationSites: typeof import('./../src/components/dataset/dataset-publication-sites.vue')['default']
    DatasetRestUploadActions: typeof import('./../src/components/dataset/dataset-rest-upload-actions.vue')['default']
    DatasetSchemaView: typeof import('./../src/components/dataset/dataset-schema-view.vue')['default']
    DatasetSearchFiles: typeof import('./../src/components/dataset/dataset-search-files.vue')['default']
    DatasetSelect: typeof import('./../src/components/dataset/select/dataset-select.vue')['default']
    DatasetSelectCards: typeof import('./../src/components/dataset/select/dataset-select-cards.vue')['default']
    DatasetSelectCols: typeof import('./../src/components/dataset/dataset-select-cols.vue')['default']
    DatasetStatus: typeof import('./../src/components/dataset/dataset-status.vue')['default']
    DatasetStoreProvider: typeof import('./../src/components/provide/dataset-store-provider.vue')['default']
    DatasetTable: typeof import('./../src/components/dataset/table/dataset-table.vue')['default']
    DatasetTableCell: typeof import('./../src/components/dataset/table/dataset-table-cell.vue')['default']
    DatasetTableHeaderActions: typeof import('./../src/components/dataset/table/dataset-table-header-actions.vue')['default']
    DatasetTableHeaderMenu: typeof import('./../src/components/dataset/table/dataset-table-header-menu.vue')['default']
    DatasetTableResultActions: typeof import('./../src/components/dataset/table/dataset-table-result-actions.vue')['default']
    DatasetTableSelectDisplay: typeof import('./../src/components/dataset/table/dataset-table-select-display.vue')['default']
    DatasetThumbnails: typeof import('./../src/components/dataset/dataset-thumbnails.vue')['default']
    JournalView: typeof import('./../src/components/journal-view.vue')['default']
    LayoutScrollToTop: typeof import('./../src/components/layout/layout-scroll-to-top.vue')['default']
    OwnerDepartment: typeof import('./../src/components/owner/owner-department.vue')['default']
    OwnerShort: typeof import('./../src/components/owner/owner-short.vue')['default']
    ResourceVisibility: typeof import('./../src/components/resource-visibility.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsApiKeys: typeof import('./../src/components/settings/settings-api-keys.vue')['default']
    SettingsApiKeyUseMenu: typeof import('./../src/components/settings/settings-api-key-use-menu.vue')['default']
    SettingsLicenses: typeof import('./../src/components/settings/settings-licenses.vue')['default']
    SettingsTopics: typeof import('./../src/components/settings/settings-topics.vue')['default']
    SettingsWebhooks: typeof import('./../src/components/settings/settings-webhooks.vue')['default']
    TutorialAlert: typeof import('./../src/components/tutorial/tutorial-alert.vue')['default']
    WorkflowUpdateDataset: typeof import('./../src/components/workflow/workflow-update-dataset.vue')['default']
  }
}
