/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/application/[id]/config': RouteRecordInfo<'/application/[id]/config', '/application/:id/config', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dataset/[id]/fields': RouteRecordInfo<'/dataset/[id]/fields', '/dataset/:id/fields', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dataset/[id]/form': RouteRecordInfo<'/dataset/[id]/form', '/dataset/:id/form', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dataset/[id]/journal': RouteRecordInfo<'/dataset/[id]/journal', '/dataset/:id/journal', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dataset/[id]/map': RouteRecordInfo<'/dataset/[id]/map', '/dataset/:id/map', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dataset/[id]/table': RouteRecordInfo<'/dataset/[id]/table', '/dataset/:id/table', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dataset/[id]/table-edit': RouteRecordInfo<'/dataset/[id]/table-edit', '/dataset/:id/table-edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dev': RouteRecordInfo<'/dev', '/dev', Record<never, never>, Record<never, never>>,
    '/settings/[type]/[id]/api-keys': RouteRecordInfo<'/settings/[type]/[id]/api-keys', '/settings/:type/:id/api-keys', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/settings/[type]/[id]/licenses': RouteRecordInfo<'/settings/[type]/[id]/licenses', '/settings/:type/:id/licenses', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/settings/[type]/[id]/topics': RouteRecordInfo<'/settings/[type]/[id]/topics', '/settings/:type/:id/topics', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/settings/[type]/[id]/webhooks': RouteRecordInfo<'/settings/[type]/[id]/webhooks', '/settings/:type/:id/webhooks', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/workflow/update-dataset': RouteRecordInfo<'/workflow/update-dataset', '/workflow/update-dataset', Record<never, never>, Record<never, never>>,
  }
}
