/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ParquetWriter {
  constructor(basicSchema: Array<BasicSchemaProperty>, buffer: Buffer)
  addRows(rows: Array<object>): void
  finish(): void
}
export type JsParquetWriter = ParquetWriter

export interface BasicSchemaProperty {
  key: string
  type: string
  format?: string
  'x-required': boolean
}
