/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ParquetWriter {
  constructor(basicSchema: Array<BasicSchemaProperty>)
  addRows(rows: Array<object>): Buffer
  finish(): Buffer
}
export type JsParquetWriter = ParquetWriter

export interface BasicSchemaProperty {
  key: string
  type: string
  format?: string
  required?: boolean
}
