name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: Prepare docker image tags
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} 
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare BUILD.json
      run: |
        echo '{"version": "${{github.ref_name}}", "repository": "${{github.server_url}}/${{github.repository}}", "commit": "${{github.sha}}", "date": "'$(date -Is)'"}' > BUILD.json
        cat BUILD.json

    - name: Build and push docker images
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        platforms: linux/amd64
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/buildcache,mode=max
    
    - name: Stop test dependencies
      run: docker compose stop

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}